query About($slug: String) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

query AllAbouts($first: IntType = 500, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		...AboutFragment
	}
	_allAboutsMeta {
		count
	}
}

fragment AboutFragment on AboutRecord {
	content {
		value
		links
		blocks {
			... on ImageRecord {
				image {
					...ImageFragment
				}
			}
		}
	}
	headline
	slug
	title
}

fragment AboutLightFragment on AboutRecord {
	content {
		value
		links
		blocks {
			... on ImageRecord {
				image {
					...ImageFragment
				}
			}
		}
	}
	headline
	slug
	title
}
