query AuthUser {
  authUser {
    ...AuthUserFragment
  }
}

query AllAuthUsers($first: IntType = 500, $skip: IntType = 0) {
  allAuthUsers(first: $first, skip: $skip) {
    ...AuthUserFragment
  }
  _allAuthUsersMeta {
    count
  }
}

fragment AuthUserFragment on AuthUserRecord {
  email
  emailVerified
  image {
    ...ImageFragment
  }
  name
}

fragment AuthUserLightFragment on AuthUserRecord {
  email
  emailVerified
  image {
    ...ImageFragment
  }
  name
}
