query Booking($id: ItemId!) {
	booking(filter: { id: { eq: $id } }) {
		...BookingFragment
	}
}

query AllBookings($first: IntType = 500, $skip: IntType = 0) {
	allBookings(first: $first, skip: $skip) {
		...BookingLightFragment
	}
	_allBookingsMeta {
		count
	}
}

query AllBookingsByMember($first: IntType = 500, $skip: IntType = 0, $memberId: ItemId) {
	allBookings(first: $first, skip: $skip, filter: { member: { eq: $memberId } }) {
		...BookingLightFragment
	}
	_allBookingsMeta(filter: { member: { eq: $memberId } }) {
		count
	}
}
query PastBookingsByMember($first: IntType = 500, $skip: IntType = 0, $memberId: ItemId, $now: DateTime) {
	allBookings(first: $first, skip: $skip, filter: { member: { eq: $memberId }, start: { lte: $now } }) {
		...BookingLightFragment
	}
	_allBookingsMeta(filter: { member: { eq: $memberId }, start: { lte: $now } }) {
		count
	}
}
query FutureBookingsByMember($first: IntType = 500, $skip: IntType = 0, $memberId: ItemId, $now: DateTime) {
	allBookings(first: $first, skip: $skip, filter: { member: { eq: $memberId }, start: { gte: $now } }) {
		...BookingLightFragment
	}
	_allBookingsMeta(filter: { member: { eq: $memberId }, start: { gte: $now } }) {
		count
	}
}

fragment BookingFragment on BookingRecord {
	id
	member {
		... on MemberRecord {
			...MemberFragment
		}
	}
	note
	reported
	start
	end
	workshop {
		... on WorkshopRecord {
			...WorkshopFragment
		}
	}
	equipment {
		...EquipmentLightFragment
	}
}

fragment BookingLightFragment on BookingRecord {
	id
	end
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	note
	reported
	start
	workshop {
		... on WorkshopRecord {
			email
			image {
				...ImageFragment
			}
			priceDay
			priceHour
			priceMonth
			priceWeek
			title
			titleLong
		}
	}
	equipment {
		...EquipmentLightFragment
	}
}
