query Contact {
	contact {
		id
		title
		content {
			blocks {
				__typename
				... on StaffRecord {
					id
					staffList {
						id
						text {
							blocks
							links
							value
						}
					}
				}
				... on ImageRecord {
					id
					image {
						...ImageFragment
					}
				}
			}
			inlineBlocks
			links
			value
			blocks {
				__typename
				... on StaffRecord {
					staffList {
						__typename
						id
						... on StaffItemRecord {
							text {
								blocks
								inlineBlocks
								links
								value
							}
						}
					}
				}
			}
		}
	}
}
