query Contact {
	contact {
		id
		title
		content {
			blocks {
				__typename
				... on StaffRecord {
					id
					staffList {
						id
						text {
							blocks
							links
							value
						}
						image {
							...ImageFragment
						}
					}
				}
			}
			inlineBlocks
			links
			value
			blocks {
				__typename
				id
				... on StaffRecord {
					staffList {
						__typename
						id
						... on StaffItemRecord {
							image {
								...ImageFragment
							}
							text {
								blocks
								inlineBlocks
								links
								value
							}
						}
					}
				}
			}
		}
	}
}
