query Course($slug: String) {
	course(filter: { slug: { eq: $slug } }) {
		...CourseFragment
	}
}
query CourseById($id: ItemId) {
	course(filter: { id: { eq: $id } }) {
		...CourseFragment
	}
}

query AllCourses($first: IntType = 500, $skip: IntType = 0) {
	allCourses(first: $first, skip: $skip) {
		...CourseFragment
	}
	_allCoursesMeta {
		count
	}
}

query AllCoursesByMember($first: IntType = 500, $skip: IntType = 0, $memberId: ItemId) {
	allCourses(first: $first, skip: $skip, filter: { member: { eq: $memberId } }) {
		...CourseLightFragment
	}
	_allCoursesMeta(filter: { member: { eq: $memberId } }) {
		count
	}
}

query AllComingCourses($today: DateTime) {
	allCourses(filter: { start: { gte: $today } }, first: 4) {
		...CourseLightFragment
	}
}

fragment CourseFragment on CourseRecord {
	id
	title
	image {
		...ImageFragment
	}
	intro {
		blocks
		inlineBlocks
		links
		value
	}
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	price
	start
	end
	workshop {
		... on WorkshopRecord {
			...WorkshopLightFragment
		}
	}
	slug
	_updatedAt
	_status
}

fragment CourseLightFragment on CourseRecord {
	id
	title
	image {
		...ImageFragment
	}
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	price
	start
	end
	workshop {
		... on WorkshopRecord {
			...WorkshopLightFragment
		}
	}
	slug
	_updatedAt
	_status
}
