query Member($email: String!) {
	member(filter: { email: { eq: $email } }) {
		...MemberFragment
	}
}

query AllMembers($first: IntType = 500, $skip: IntType = 0) {
	allMembers(first: $first, skip: $skip) {
		...MemberFragment
	}
	_allMembersMeta {
		count
	}
}

fragment MemberFragment on MemberRecord {
	firstName
	lastName
	email
	phone
	phoneHome
	sex
	address
	postalCode
	city
	ssa
	cardNumber
	compartment
	workshops {
		...WorkshopLightFragment
	}
}

fragment MemberLightFragment on MemberRecord {
	firstName
	lastName
	email
}
