query Member {
  member {
    ...MemberFragment
  }
}

query AllMembers($first: IntType = 500, $skip: IntType = 0) {
  allMembers(first: $first, skip: $skip) {
    ...MemberFragment
  }
  _allMembersMeta {
    count
  }
}

fragment MemberFragment on MemberRecord {
  email
  name
}

fragment MemberLightFragment on MemberRecord {
  email
  name
}
