query Report {
	report {
		...ReportFragment
	}
}

query AllReports($first: IntType = 500, $skip: IntType = 0) {
	allReports(first: $first, skip: $skip) {
		...ReportFragment
	}
	_allReportsMeta {
		count
	}
}

query AllReportsByMember($first: IntType = 500, $skip: IntType = 0, $memberId: ItemId) {
	allReports(first: $first, skip: $skip, filter: { member: { eq: $memberId } }) {
		...ReportFragment
	}
	_allReportsMeta(filter: { member: { eq: $memberId } }) {
		count
	}
}

query AllReportsByRange($first: IntType = 500, $skip: IntType = 0, $start: Date, $end: Date) {
	allReports(first: $first, skip: $skip, filter: { date: { gte: $start, lte: $end } }) {
		...ReportFragment
	}
	_allReportsMeta(filter: { date: { gte: $start, lte: $end } }) {
		count
	}
}

fragment ReportFragment on ReportRecord {
	id
	date
	days
	hours
	extraCost
	assistants {
		... on AssistantRecord {
			id
			days
			hours
		}
	}
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	booking {
		...BookingLightFragment
	}
	workshop {
		... on WorkshopRecord {
			...WorkshopLightFragment
		}
	}
}

fragment ReportLightFragment on ReportRecord {
	id
	assistants {
		... on AssistantRecord {
			...AssistantFragment
		}
	}
	date
	days
	hours
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	workshop {
		... on WorkshopRecord {
			...WorkshopFragment
		}
	}
}

fragment AssistantFragment on AssistantRecord {
	id
	days
	hours
}
