query Report {
	report {
		...ReportFragment
	}
}

query AllReports($first: IntType = 500, $skip: IntType = 0) {
	allReports(first: $first, skip: $skip) {
		...ReportFragment
	}
	_allReportsMeta {
		count
	}
}

fragment ReportFragment on ReportRecord {
	id
	date
	days
	hours
	assistants {
		... on AssistantRecord {
			id
			days
			hours
		}
	}
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	workshop {
		... on WorkshopRecord {
			...WorkshopLightFragment
		}
	}
}

fragment ReportLightFragment on ReportRecord {
	id
	assistants {
		... on AssistantRecord {
			...AssistantFragment
		}
	}
	date
	days
	hours
	member {
		... on MemberRecord {
			...MemberLightFragment
		}
	}
	workshop {
		... on WorkshopRecord {
			...WorkshopFragment
		}
	}
}

fragment AssistantFragment on AssistantRecord {
	id
	days
	hours
}
