query SignUpStart {
	signUpStart {
		__typename
		_modelApiKey
		id
		title
		intro {
			blocks
			inlineBlocks
			links
			value
		}
		text {
			blocks
			inlineBlocks
			links
			value
		}
	}
	signUpFormHelp {
		__typename
		_modelApiKey
		education
		artisticPractice
	}
}
