query Start {
	start {
		...StartFragment
	}
	allWorkshops(first: 500) {
		...WorkshopLightFragment
	}
}

fragment StartFragment on StartRecord {
	title
	gallery {
		... on GalleryImageRecord {
			image {
				...ImageFragment
			}
			caption {
				blocks
				inlineBlocks
				links
				value
			}
		}
	}
	aboutUs {
		blocks
		inlineBlocks
		links
		value
	}
}
