query WorkshopStart {
	workshopsStart {
		id
		title
		intro {
			blocks
			inlineBlocks
			links
			value
		}
	}
}
query Workshop($slug: String) {
	workshop(filter: { slug: { eq: $slug } }) {
		...WorkshopFragment
	}
}

query AllWorkshops($first: IntType = 500, $skip: IntType = 0) {
	allWorkshops(first: $first, skip: $skip, orderBy: [title_ASC]) {
		...WorkshopFragment
	}
	_allWorkshopsMeta {
		count
	}
}

fragment WorkshopFragment on WorkshopRecord {
	id
	title
	titleLong
	intro {
		blocks
		inlineBlocks
		links
		value
	}
	text {
		blocks
		inlineBlocks
		links
		value
	}
	email
	image {
		...ImageFragment
	}
	equipment {
		...EquipmentLightFragment
	}
	priceDay
	priceHour
	priceMonth
	priceWeek
	slug
}

fragment WorkshopLightFragment on WorkshopRecord {
	id
	title
	titleLong
	image {
		...ImageFragment
	}
	slug
}
