query WorkshopStart {
	workshopsStart {
		id
		title
		intro {
			blocks
			inlineBlocks
			links
			value
		}
	}
}
query Workshop($slug: String) {
	workshop(filter: { slug: { eq: $slug } }) {
		...WorkshopFragment
	}
}

query AllWorkshops($first: IntType = 500, $skip: IntType = 0) {
	allWorkshops(first: $first, skip: $skip, orderBy: [title_ASC]) {
		...WorkshopFragment
	}
	_allWorkshopsMeta {
		count
	}
}
query AllBookableWorkshops($first: IntType = 500, $skip: IntType = 0) {
	allWorkshops(
		first: $first
		skip: $skip
		orderBy: [title_ASC]
		filter: { hideFromBooking: { eq: false } }
	) {
		...WorkshopFragment
	}
	_allWorkshopsMeta(filter: { hideFromBooking: { eq: false } }) {
		count
	}
}

query AllWorkshopsForm($first: IntType = 500, $skip: IntType = 0) {
	allWorkshops(
		first: $first
		skip: $skip
		orderBy: [title_ASC]
		filter: { hideFromBooking: { eq: false } }
	) {
		...WorkshopFormFragment
	}
	_allWorkshopsMeta(filter: { hideFromBooking: { eq: false } }) {
		count
	}
	bookingHelp {
		workshop {
			blocks
			links
			value
		}
		calendar {
			blocks
			links
			value
		}
		equipment {
			blocks
			links
			value
		}
	}
}

fragment WorkshopFragment on WorkshopRecord {
	id
	title
	titleLong
	intro {
		blocks
		inlineBlocks
		links
		value
	}
	text {
		blocks
		inlineBlocks
		links
		value
	}
	email
	image {
		...ImageFragment
	}
	gallery {
		...ImageFragment
	}
	equipment {
		...EquipmentLightFragment
	}
	priceDay
	priceHour
	priceMonth
	priceWeek
	hideFromBooking
	slug
}

fragment WorkshopFormFragment on WorkshopRecord {
	id
	title
	titleLong
	image {
		...ImageThumbnailFormFragment
	}
	gallery {
		...ImageFragment
	}
	equipment {
		...EquipmentLightFragment
	}
	priceDay
	priceHour
	priceMonth
	priceWeek
	slug
}

fragment WorkshopLightFragment on WorkshopRecord {
	id
	title
	titleLong
	priceDay
	priceHour
	priceMonth
	priceWeek

	image {
		...ImageFragment
	}
	slug
}
