export const mapKeysTransformInput = {
	id: 'id',
	name: 'name',
	start: 'start',
	prefix: 'prefix',
	key: 'key',
	//userId: 'user_id',
	refillInterval: 'refill_interval',
	refillAmount: 'refill_amount',
	lastRefillAt: 'last_refill_at',
	enabled: 'enabled',
	rateLimitEnabled: 'rate_limit_enabled',
	rateLimitTimeWindow: 'rate_limit_time_window',
	rateLimitMax: 'rate_limit_max',
	requestCount: 'request_count',
	remaining: 'remaining',
	lastRequest: 'last_request',
	//expiresAt: 'expires_at',
	//createdAt: 'created_at',
	//updatedAt: 'updated_at',
	permissions: 'permissions',
	metadata: 'metadata',
};

export const mapKeysTransformOutput = {
	id: 'id',
	name: 'name',
	start: 'start',
	prefix: 'prefix',
	key: 'key',
	//userId: 'user_id',
	refillInterval: 'refill_interval',
	refillAmount: 'refill_amount',
	lastRefillAt: 'last_refill_at',
	enabled: 'enabled',
	rateLimitEnabled: 'rate_limit_enabled',
	rateLimitTimeWindow: 'rate_limit_time_window',
	rateLimitMax: 'rate_limit_max',
	requestCount: 'request_count',
	remaining: 'remaining',
	lastRequest: 'last_request',
	//expiresAt: 'expires_at',
	//createdAt: 'created_at',
	//updatedAt: 'updated_at',
	permissions: 'permissions',
	metadata: 'metadata',
};
